# Generated by Django 4.1 on 2024-06-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('autor', models.CharField(max_length=128)),
                ('cantidad_paginas', models.IntegerField()),
                ('editorial', models.CharField(max_length=128)),
            ],
        ),
    ]
