# Generated by Django 4.1 on 2024-06-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descatalogado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('libros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro_api.libro')),
            ],
        ),
    ]
