# Generated by Django 4.1 on 2024-06-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro_api', '0002_libro_descatalogado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descatalogado',
            field=models.BooleanField(default=True),
        ),
    ]
