# Generated by Django 4.1 on 2024-06-17 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro_api', '0004_alter_libro_descatalogado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='libros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libro_api.libro'),
        ),
    ]
