# Generated by Django 4.1 on 2024-06-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro_api', '0005_alter_user_libros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='titulo',
        ),
    ]
