# Generated by Django 4.1 on 2024-06-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro_api', '0007_rename_titulo_user_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='libros',
        ),
        migrations.AddField(
            model_name='user',
            name='libros',
            field=models.ManyToManyField(to='libro_api.libro'),
        ),
    ]
