# Generated by Django 4.1 on 2024-06-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro_api', '0008_remove_user_libros_user_libros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.AlterField(
            model_name='user',
            name='libros',
            field=models.ManyToManyField(blank=True, to='libro_api.libro'),
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('libros', models.ManyToManyField(blank=True, to='libro_api.libro')),
            ],
        ),
    ]
