# Generated by Django 4.1 on 2024-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro_api', '0009_remove_libro_autor_alter_user_libros_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='libros',
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(blank=True, to='libro_api.autor'),
        ),
    ]
