# Generated by Django 4.1 on 2024-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro_api', '0011_editorial_remove_libro_autores_autor_libros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='ciudad',
            field=models.CharField(default='desconocida', max_length=128),
        ),
    ]
